import {Ocean,PRESETS} from './ocean.js';
import {RippleField,Buoy,Spray} from './interaction.js';
import {NativeBackend,ThreeBackend} from './backend.js';
import {oceanGeometry,sphereGeometry} from './geometry.js';
import {clamp,V,perspective,lookAt,matmul,cameraBasis,lerp} from './math.js';
const $=s=>document.querySelector(s),params=new URLSearchParams(window.__QUERY__||location.search),capture=params.has('capture');
let sceneKey=params.get('scene')||'dawn';if(!PRESETS[sceneKey])sceneKey='dawn';
let showBuoy=false,debug=0,paused=false,cinematic=true,filmTime=0,simTime=57,speed=1,zoom=1,yaw=0,pitch=0,last=0,frameNumber=0,resScale=1;
const canvas=$('#water'),geometry=oceanGeometry(params.get('quality')==='high'?280:200,params.get('quality')==='high'?512:320,12500);
let backend;
async function chooseBackend(){if(!params.has('offline')){if(window.THREE)return new ThreeBackend(window.THREE,canvas,geometry);for(const url of ['./vendor/three.module.js','https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js']){try{const T=await Promise.race([import(url),new Promise((_,reject)=>setTimeout(()=>reject(Error('Three.js dependency unavailable')),url.startsWith('http')?3500:400))]);return new ThreeBackend(T,canvas,geometry);}catch(err){console.info(err.message);}}}return new NativeBackend(canvas,geometry);}
async function assetBytes(path){if(window.__ASSETS__&&window.__ASSETS__[path]){const entry=window.__ASSETS__[path],raw=Uint8Array.from(atob(entry.data),c=>c.charCodeAt(0));if(entry.gzip)return new Uint8Array(await new Response(new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer());return raw;}const r=await fetch(path);if(!r.ok)throw Error('Could not load '+path);return new Uint8Array(await r.arrayBuffer());}
const skyData={};
async function loadAssets(){for(const name of ['dawn','blue','storm']){const raw=await assetBytes('assets/'+name+'.rgba16f');skyData[name]=new Uint16Array(raw.buffer,raw.byteOffset,raw.byteLength/2);}const raw=await assetBytes('assets/micro.png'),bitmap=await createImageBitmap(new Blob([raw],{type:'image/png'}));backend.texture('uMicro',bitmap.width,bitmap.height,bitmap,{image:true});}
const ocean=new Ocean(sceneKey,128),ripples=new RippleField(),buoy=new Buoy(6,-14),spray=new Spray();
const width=()=>capture?Number(params.get('width')||1280):Math.floor(innerWidth*Math.min(devicePixelRatio,1.5)*resScale),height=()=>capture?Number(params.get('height')||720):Math.floor(innerHeight*Math.min(devicePixelRatio,1.5)*resScale);
function resize(){backend.resize(width(),height());}
function upload(){for(let i=0;i<3;i++){const c=ocean.cascades[i];backend.texture('uDisplacement'+i,c.n,c.n,c.displacement);backend.texture('uDerivativeX'+i,c.n,c.n,c.derivativeX);backend.texture('uDerivativeZ'+i,c.n,c.n,c.derivativeZ);}backend.texture('uRipple',ripples.n,ripples.n,ripples.data,{repeat:false});}
function setPreset(key){if(!PRESETS[key])return;sceneKey=key;ocean.reset(key);ripples.reset();simTime=57;filmTime=0;spray.life.fill(0);ocean.step(simTime-7,0);for(let i=0;i<42;i++)ocean.step(simTime-7+(i+1)/6,1/6);backend.texture('uSky',2048,1024,skyData[ocean.preset.sky],{half:true});$('#scene-title').textContent=ocean.preset.name;$('#scene-subtitle').textContent=ocean.preset.subtitle;document.querySelectorAll('[data-scene]').forEach(el=>el.classList.toggle('selected',el.dataset.scene===key));upload();}
function camera(t){if(cameraOverride)return cameraOverride;const storm=sceneKey==='storm',h=storm?4.8:4.8;let eye,target,fov=55;const local=t%24;
 if(local<8){const s=local/8;eye=[14-s*9,h+Math.sin(s*Math.PI)*.65,30-s*12];target=[-32+s*3,0,-68];fov=54;}
 else if(local<16){const s=(local-8)/8;eye=[-30+s*11,storm?16:9,26-s*5];target=[-70,storm?-.7:-.2,-84];fov=44;}
 else{const s=(local-16)/8;eye=[20-s*12,storm?44:30,26-s*11];target=[-8,0,-16-s*7];fov=51;}
 if(!cinematic){eye=[Math.sin(yaw)*42*zoom,clamp(12+pitch*30,2,90)*zoom,Math.cos(yaw)*42*zoom];target=[0,0,-10];}
 else if(zoom!==1||yaw!==0){const dir=V.sub(eye,target),s=Math.sin(yaw),c=Math.cos(yaw);eye=V.add(target,[(dir[0]*c-dir[2]*s)*zoom,Math.max(1.8,dir[1]*zoom+pitch*8),(dir[0]*s+dir[2]*c)*zoom]);}
 eye[1]=Math.max(eye[1],ocean.sample(eye[0],eye[2])+1.25);return {eye,target,fov};}
let currentCamera=null,cameraOverride=null;
function draw(){const p=ocean.preset,c=currentCamera=camera(filmTime),basis=cameraBasis(c.eye,c.target),projection=perspective(c.fov*Math.PI/180,width()/height(),.10,40000),view=lookAt(c.eye,c.target),color=sceneKey==='dawn'?[2.1,1.10,.46]:sceneKey==='storm'?[.65,.71,.73]:[2.3,2.25,2.12];const values={uEye:c.eye,uViewProjection:matmul(projection,view),uForward:basis.forward,uRight:basis.right,uUp:basis.up,uTanFov:Math.tan(c.fov*Math.PI/360),uAspect:width()/height(),uSun:V.norm(p.sun),uSunColor:color,uExposure:p.exposure,uTime:simTime,uResolution:[width(),height()],uBuoyPosition:[buoy.x,buoy.y,buoy.z],uBuoyRadius:buoy.radius,uBuoyVisible:showBuoy?1:0,uWater:p.water,uDepth:p.depth,uRoughness:p.roughness,uWind:p.wind,uDebug:debug,uRippleCenter:ripples.center,uRippleSize:ripples.size,uPointScale:height()*1.35};const objects=showBuoy?sphereGeometry([buoy.x,buoy.y,buoy.z],buoy.radius,[.48,.065,.015]):null;backend.render(values,objects,spray);}
function advance(dt){const step=Math.min(dt,.1);simTime+=step;filmTime+=step;ocean.step(simTime,step);ripples.step(step);buoy.step(step,ocean.sample(buoy.x,buoy.z));spray.step(step,ocean,camera(filmTime).eye);upload();}
function diagnostics(){return {...ocean.diagnostics(),backend:backend.name,rippleVolume:ripples.mass(),rippleEnergy:ripples.energy(),sprayParticles:spray.count,buoy:{height:buoy.y,velocity:buoy.vy,submergedVolume:buoy.wetVolume},triangles:geometry.indices.length/3,resolution:[width(),height()]};}
function tick(now){const rawElapsed=last?(now-last)/1000:1/60;const elapsed=Math.min(rawElapsed,.07);last=now;if(!paused)advance(elapsed*speed);draw();frameNumber++;if(frameNumber%18===0){const d=diagnostics();$('#fps').textContent=(1/Math.max(.001,rawElapsed)).toFixed(0);$('#height-stat').textContent=d.estimateHs.toFixed(2)+' m';$('#wind-stat').textContent=ocean.preset.wind+' m/s';$('#diagnostics').textContent=JSON.stringify(d,null,2);$('#backend').textContent=backend.name;}if(!capture)requestAnimationFrame(tick);}
function bindUI(){document.querySelectorAll('[data-scene]').forEach(el=>el.addEventListener('click',()=>setPreset(el.dataset.scene)));$('#play').onclick=()=>{paused=!paused;$('#play').textContent=paused?'Play':'Pause';};$('#buoy').onclick=()=>{showBuoy=!showBuoy;$('#buoy').classList.toggle('active',showBuoy);};$('#film').onclick=()=>{cinematic=!cinematic;$('#film').classList.toggle('active',cinematic);};$('#quality').onchange=e=>{resScale=+e.target.value;resize();};$('#diagnostic-toggle').onclick=()=>$('#diagnostic-panel').classList.toggle('open');$('#speed').oninput=e=>{speed=+e.target.value;$('#speed-value').textContent=speed.toFixed(2)+'×';};$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
 let drag=null;canvas.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.004;pitch=clamp(pitch+(e.clientY-drag[1])*.004,-.8,2);drag=[e.clientX,e.clientY];});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom*Math.exp(e.deltaY*.0008),.35,4);},{passive:false});canvas.addEventListener('dblclick',e=>{const c=currentCamera,b=cameraBasis(c.eye,c.target),u=e.clientX/innerWidth*2-1,v=1-e.clientY/innerHeight*2,s=Math.tan(c.fov*Math.PI/360),ray=V.norm(V.add(b.forward,V.add(V.scale(b.right,u*innerWidth/innerHeight*s),V.scale(b.up,v*s))));if(ray[1]<-.015){const t=-c.eye[1]/ray[1];if(t<300)ripples.impulse(c.eye[0]+ray[0]*t,c.eye[2]+ray[2]*t,1.1,1.6);}});
 document.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if('123'.includes(e.key))setPreset(['dawn','blue','storm'][+e.key-1]);if(e.code==='Space'){e.preventDefault();$('#play').click();}if(e.key.toLowerCase()==='b')$('#buoy').click();if(e.key.toLowerCase()==='d')$('#diagnostic-toggle').click();if(e.key.toLowerCase()==='h')document.body.classList.toggle('hide-ui');if(e.key.toLowerCase()==='n')debug=(debug+1)%3;});
 $('#record').onclick=()=>{const stream=canvas.captureStream(30),mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime){alert('This browser does not support WebM capture.');return;}const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:16000000}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=()=>{const url=URL.createObjectURL(new Blob(chunks,{type:mime})),a=document.createElement('a');a.href=url;a.download='cybr-water-'+sceneKey+'.webm';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('#record').textContent='Record 24 s';};$('#record').textContent='Recording…';cinematic=true;filmTime=0;rec.start();setTimeout(()=>rec.stop(),24000);};
 window.addEventListener('resize',resize);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();paused=true;$('#error').textContent='Graphics context lost. Reload this page to restart the simulation.';$('#error').hidden=false;});}
try{backend=await chooseBackend();resize();await loadAssets();setPreset(sceneKey);bindUI();if(capture)document.body.classList.add('hide-ui');$('#loading').remove();$('#backend').textContent=backend.name;
 window.app={ocean,ripples,buoy,backend,diagnostics,setPreset,setDebug:v=>debug=v,setBuoy:v=>showBuoy=v,setCinematic:v=>cinematic=v,render:draw,frame:(dt=1/30)=>{advance(dt);draw();return diagnostics();},setFilmTime:t=>filmTime=t,setCamera:c=>cameraOverride=c,screenshot:()=>canvas.toDataURL('image/png'),getCamera:()=>currentCamera};window.__READY__=true;draw();if(!capture)requestAnimationFrame(tick);
}catch(error){console.error(error);$('#error').textContent=error.stack||String(error);$('#error').hidden=false;$('#loading').style.display='none';window.__ERROR__=String(error);}
