import {skyVertex,skyFragment,waterVertex,waterFragment,objectVertex,objectFragment,sprayVertex,sprayFragment} from './shaders.js';
/** Dependency-free WebGL2 renderer for offline operation and deterministic capture.
 * This is explicitly a fallback, not a reimplementation relabeled as Three.js.
 */
export class NativeBackend {
 constructor(canvas,geometry){this.canvas=canvas;this.name='WebGL2 offline renderer';const gl=this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!gl)throw Error('WebGL2 is required. Enable hardware acceleration in your browser.');gl.getExtension('EXT_color_buffer_float');this.floatLinear=!!gl.getExtension('OES_texture_float_linear');this.textures=new Map();this.programs={sky:this.program(skyVertex,skyFragment),water:this.program(waterVertex,waterFragment),object:this.program(objectVertex,objectFragment),spray:this.program(sprayVertex,sprayFragment)};this.water=this.mesh(geometry.vertices,geometry.indices);this.quad=this.mesh(new Float32Array([-1,-1,0,3,-1,0,-1,3,0]));this.objectBuffers=null;this.sprayBuffers=null;gl.clearColor(0,0,0,1);}
 program(vs,fs){const gl=this.gl;const compile=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const e=gl.getShaderInfoLog(s);gl.deleteShader(s);throw Error(e);}return s;};const p=gl.createProgram();const v=compile(gl.VERTEX_SHADER,vs),f=compile(gl.FRAGMENT_SHADER,fs);gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));const uniforms={};for(let i=0;i<gl.getProgramParameter(p,gl.ACTIVE_UNIFORMS);i++){const u=gl.getActiveUniform(p,i);uniforms[u.name]={location:gl.getUniformLocation(p,u.name),type:u.type};}return {program:p,uniforms};}
 mesh(vertices,indices=null){const gl=this.gl,b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,vertices,gl.STATIC_DRAW);let ib=null;if(indices){ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,indices,gl.STATIC_DRAW);}return {b,ib,count:indices?indices.length:vertices.length/3};}
 texture(name,width,height,data,{half=false,repeat=true,image=false}={}){const gl=this.gl;let t=this.textures.get(name);if(!t){t={handle:gl.createTexture(),width:0,height:0};this.textures.set(name,t);}gl.bindTexture(gl.TEXTURE_2D,t.handle);const linear=half||image||this.floatLinear;gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,linear?gl.LINEAR:gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,linear?gl.LINEAR:gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,repeat?gl.REPEAT:gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,name==='uSky'?gl.CLAMP_TO_EDGE:(repeat?gl.REPEAT:gl.CLAMP_TO_EDGE));gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);if(image){gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,data);}else if(t.width===width&&t.height===height){gl.texSubImage2D(gl.TEXTURE_2D,0,0,0,width,height,gl.RGBA,half?gl.HALF_FLOAT:gl.FLOAT,data);}else{gl.texImage2D(gl.TEXTURE_2D,0,half?gl.RGBA16F:gl.RGBA32F,width,height,0,gl.RGBA,half?gl.HALF_FLOAT:gl.FLOAT,data);}t.width=width;t.height=height;}
 bind(program,values){const gl=this.gl;gl.useProgram(program.program);let unit=0;for(const [name,u] of Object.entries(program.uniforms)){const texture=this.textures.get(name);if(texture){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,texture.handle);gl.uniform1i(u.location,unit++);continue;}const v=values[name];if(v===undefined)continue;switch(u.type){case gl.FLOAT:gl.uniform1f(u.location,v);break;case gl.FLOAT_VEC2:gl.uniform2fv(u.location,v);break;case gl.FLOAT_VEC3:gl.uniform3fv(u.location,v);break;case gl.FLOAT_VEC4:gl.uniform4fv(u.location,v);break;case gl.FLOAT_MAT4:gl.uniformMatrix4fv(u.location,false,v);break;}}}
 attribute(program,name,buffer,size=3){const gl=this.gl,loc=gl.getAttribLocation(program.program,name);if(loc<0)return;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0);}
 render(values,objects=null,spray=null){const gl=this.gl;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.depthMask(false);this.bind(this.programs.sky,values);this.attribute(this.programs.sky,'position',this.quad.b);gl.drawArrays(gl.TRIANGLES,0,3);
 gl.depthMask(true);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);this.bind(this.programs.water,values);this.attribute(this.programs.water,'position',this.water.b);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.water.ib);gl.drawElements(gl.TRIANGLES,this.water.count,gl.UNSIGNED_INT,0);
 if(objects){gl.disable(gl.CULL_FACE);const p=this.programs.object;this.bind(p,values);if(!this.objectBuffers)this.objectBuffers=[gl.createBuffer(),gl.createBuffer(),gl.createBuffer()];[objects.vertices,objects.normals,objects.colors].forEach((data,i)=>{gl.bindBuffer(gl.ARRAY_BUFFER,this.objectBuffers[i]);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);this.attribute(p,['position','normal','color'][i],this.objectBuffers[i]);});gl.drawArrays(gl.TRIANGLES,0,objects.vertices.length/3);}
 if(spray&&spray.count){const p=this.programs.spray;this.bind(p,values);if(!this.sprayBuffers)this.sprayBuffers=[gl.createBuffer(),gl.createBuffer()];[spray.position,spray.info].forEach((data,i)=>{gl.bindBuffer(gl.ARRAY_BUFFER,this.sprayBuffers[i]);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);this.attribute(p,i?'aInfo':'position',this.sprayBuffers[i],i?2:3);});gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.drawArrays(gl.POINTS,0,spray.max);gl.depthMask(true);gl.disable(gl.BLEND);}
 }
 resize(w,h){this.canvas.width=w;this.canvas.height=h;}
 dispose(){const gl=this.gl;for(const t of this.textures.values())gl.deleteTexture(t.handle);for(const p of Object.values(this.programs))gl.deleteProgram(p.program);gl.deleteBuffer(this.water.b);gl.deleteBuffer(this.water.ib);gl.deleteBuffer(this.quad.b);for(const b of [...(this.objectBuffers||[]),...(this.sprayBuffers||[])])gl.deleteBuffer(b);}
}
/** Three.js adapter: genuine WebGLRenderer, scene, meshes and data textures.
 * Its GLSL, uniforms, meshes and field buffers are shared with the tested fallback.
 */
export class ThreeBackend {
 constructor(THREE,canvas,geometry){this.T=THREE;this.canvas=canvas;this.name='Three.js r'+THREE.REVISION;this.textures=new Map();this.materials=[];this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});this.renderer.autoClear=false;this.renderer.setPixelRatio(1);this.renderer.outputColorSpace=THREE.LinearSRGBColorSpace;this.scene=new THREE.Scene();this.camera=new THREE.Camera();
 const create=(vertexShader,fragmentShader)=>{const m=new THREE.RawShaderMaterial({vertexShader:vertexShader.replace('#version 300 es',''),fragmentShader:fragmentShader.replace('#version 300 es',''),glslVersion:THREE.GLSL3,uniforms:{},depthTest:true,depthWrite:true});this.materials.push(m);return m;};
 this.skyMaterial=create(skyVertex,skyFragment);this.skyMaterial.depthTest=false;this.skyMaterial.depthWrite=false;const skygeo=new THREE.BufferGeometry();skygeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array([-1,-1,0,3,-1,0,-1,3,0]),3));this.sky=new THREE.Mesh(skygeo,this.skyMaterial);this.sky.frustumCulled=false;this.sky.renderOrder=-100;this.scene.add(this.sky);
 this.waterMaterial=create(waterVertex,waterFragment);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(geometry.vertices,3));geo.setIndex(new THREE.BufferAttribute(geometry.indices,1));this.water=new THREE.Mesh(geo,this.waterMaterial);this.water.frustumCulled=false;this.scene.add(this.water);
 this.objectMaterial=create(objectVertex,objectFragment);this.objectMaterial.side=THREE.DoubleSide;this.object=new THREE.Mesh(new THREE.BufferGeometry(),this.objectMaterial);this.object.frustumCulled=false;this.scene.add(this.object);
 this.sprayMaterial=create(sprayVertex,sprayFragment);this.sprayMaterial.transparent=true;this.sprayMaterial.depthWrite=false;this.spray=new THREE.Points(new THREE.BufferGeometry(),this.sprayMaterial);this.spray.frustumCulled=false;this.scene.add(this.spray);
 }
 texture(name,width,height,data,{half=false,repeat=true,image=false}={}){const T=this.T;let t=this.textures.get(name);if(!t){t=image?new T.Texture(data):new T.DataTexture(data,width,height,T.RGBAFormat,half?T.HalfFloatType:T.FloatType);t.flipY=false;t.minFilter=T.LinearFilter;t.magFilter=T.LinearFilter;t.generateMipmaps=false;t.wrapS=repeat?T.RepeatWrapping:T.ClampToEdgeWrapping;t.wrapT=name==='uSky'?T.ClampToEdgeWrapping:t.wrapS;t.colorSpace=T.NoColorSpace;this.textures.set(name,t);}else if(image)t.image=data;else{t.image.data=data;t.image.width=width;t.image.height=height;}t.needsUpdate=true;for(const m of this.materials)m.uniforms[name]={value:t};}
 render(values,objects=null,spray=null){for(const m of this.materials){for(const [key,val] of Object.entries(values)){if(m.uniforms[key])m.uniforms[key].value=val;else m.uniforms[key]={value:val};}m.uniformsNeedUpdate=true;}
 this.object.visible=!!objects;if(objects){for(const [name,array] of [['position',objects.vertices],['normal',objects.normals],['color',objects.colors]]){const old=this.object.geometry.getAttribute(name);if(old&&old.array.length===array.length){old.array.set(array);old.needsUpdate=true;}else this.object.geometry.setAttribute(name,new this.T.BufferAttribute(array,3));}}
 this.spray.visible=!!spray&&spray.count>0;if(spray){for(const [name,array,size] of [['position',spray.position,3],['aInfo',spray.info,2]]){const old=this.spray.geometry.getAttribute(name);if(old){old.array.set(array);old.needsUpdate=true;}else this.spray.geometry.setAttribute(name,new this.T.BufferAttribute(array,size));}}
 this.renderer.clear();this.renderer.render(this.scene,this.camera);}
 resize(w,h){this.renderer.setSize(w,h,false);}
 dispose(){for(const m of this.materials)m.dispose();for(const t of this.textures.values())t.dispose();for(const obj of [this.sky,this.water,this.object,this.spray])obj.geometry.dispose();this.renderer.dispose();}
}
